package com.eshore.khala.product.dao;

import com.eshore.khala.core.data.api.dao.IBaseDao;
import com.eshore.khala.product.pojo.Category;
/**
*generated by tools 
*
*/
public interface ICategoryDao extends IBaseDao<Category> {

}
